# Generated by Django 5.0.6 on 2024-06-20 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_chats_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='plot',
            field=models.ImageField(blank=True, null=True, upload_to='reports/media/'),
        ),
        migrations.CreateModel(
            name='ReportText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
        ),
    ]
